# Generated by Django 5.1.5 on 2025-02-21 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_deliveryaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
