# Generated by Django 5.1.5 on 2025-02-22 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_deliveryaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.deliveryaddress'),
        ),
    ]
